language: python

before_script:
    - sudo apt-get install -y mpd
    - sed -i "s%^music_directory.*%music_directory $(pwd)/tests/fixtures/mp3/%" mpd.conf
    - mpd mpd.conf

script: python tests/main.py
