language: python
python:
    - "2.6"
    - "2.7"

install: "pip install -r requirements/project.txt -r requirements/tests.txt"

before_script:
    - sudo apt-get install -y mpd
    - sed -i "s%^music_directory.*%music_directory \"$(pwd)/tests/fixtures/mp3/\"%" mpd.conf
    - mpd mpd.conf

script: python tests/main.py
