language: python
python:
    - "2.6"
    - "2.7"

install: "pip install -r requirements/project.txt -r requirements/tests.txt"

before_script:
    - sudo apt-get install -y mpd
    - sudo service mpd stop
    - mkdir ~/.mpd/
    - touch ~/.mpd/database
    - sed -i "s%^music_directory.*%music_directory \"$(pwd)/music/\"%" mpd.conf
    - mpd mpd.conf

script: python tests/main.py
