language: python
python:
    - "2.7"

install: "pip install -r requirements/project.txt -r requirements/tests.txt"

before_script:
    - sudo apt-get install -y mpd libav-tools libavcodec-extra-53
    - sudo service mpd stop
    - mkdir ~/.mpd/
    - touch ~/.mpd/database
    - mkdir -p music/mp3
    - cp tests/fixtures/mp3/* music/mp3
    - sed -i "s%^music_directory.*%music_directory \"$(pwd)/music/\"%" mpd.conf
    - mpd mpd.conf
    - npm install karma

script:
    - coverage run --source . tests/main.py
    - karma start --single-run --browsers PhantomJS

after_success:
    coveralls
