language: python
python:
    - "2.7"

install: "pip install -r requirements.txt -r requirements_tests.txt"

before_script:
    - sudo apt-get update
    - sudo apt-get install -y mpd libav-tools libavcodec-extra-53
    - sudo service mpd stop
    - mkdir ~/.mpd/
    - touch ~/.mpd/database
    - mkdir -p music/mp3
    - cp -R tests/fixtures/mp3/* music/mp3
    - sed -i "s%^music_directory.*%music_directory \"$(pwd)/music/\"%" mpd.conf
    - mpd mpd.conf
    - python server.py &
    - npm install
    - export PATH=node_modules/.bin:${PATH}

script:
    - coverage run --source . tests/main.py
    - phantomjs static/js/tests/runner-list.js http://localhost:5000/tests

after_success:
    coveralls
